title: "Jaya Krishna Vamsi"
description: "Personal site to showcase projects, interests, and blogs"
author: "Jaya Krishna Vamsi"
email: "jayakrishnavamsi4@gmail.com"
github_username: JayaKrishnaVamsi
linkedin_username: jaya-krishna-vamsi-sarab-6b4a77220

theme: minima   # GitHub-supported theme

# Navigation menu
header_pages:
  - index.md
  - projects.md
  - interests.md
  - blog.md
