title: "Jaya Krishna Vamsi"
description: "Personal site to showcase projects, interests, and blogs"
author: "Jaya Krishna Vamsi"
email: "your-email@example.com"
github_username: JayaKrishnaVamsi
linkedin_username: your-linkedin

theme: minima   # GitHub-supported theme

# Navigation menu
header_pages:
  - index.md
  - projects.md
  - interests.md
  - blog.md
