title: "Home"
description: "Personal site to showcase projects, interests, and blogs"
baseurl: "" # keep empty for user.github.io
url: "https://JayaKrishnaVamsi.github.io"

nav:
  - name: "Home"
    link: /
  - name: "Projects"
    link: /projects/
  - name: "Hobbies"
    link: /interests/
  - name: "Blog"
    link: /blog/

theme: null   # disable default themes
